//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Author.rc
//
#define IDR_MANIFEST                    1
#define IDD_AUTHOR_DIALOG               102
#define IDD_OPT_RECDLG                  103
#define IDD_OPT_PENFOLDERDLG            104
#define IDD_OPT_HOTKEYDLG               105
#define IDD_OPT_ABOUTDLG                106
#define IDD_OPT_TOOLBARDLG              107
#define IDW_SLIDELIST                   108
#define IDW_SLIDELIST_CLIPLIST          109
#define IDR_MAINFRAME                   128
#define IDD_SPLASH_DIALOG               129
#define IDD_PENSELECTDLG                130
#define IDD_ERASERSELECTDLG             131
#define IDD_COLORSELECTDLG              132
#define IDD_LINEWEIGHTSELECTDLG         133
#define IDD_DIAGRAMSELECTDLG            134
#define IDD_BOARDSELECTDLG              135
#define IDD_SLIDEMENUDLG                136
#define IDD_BOARDDLG                    137
#define IDB_SPLASH                      140
#define IDB_MODEBTN                     141
#define IDB_PENCIL                      142
#define IDB_PPTNEXT                     143
#define IDB_PPTPREV                     144
#define IDB_BLACKBOARD                  145
#define IDB_LINEWEIGHTBTN               146
#define IDB_ZOOMBTN                     147
#define IDB_BGIMAGE                     148
#define IDB_COLORBTN                    149
#define IDB_ERASER                      150
#define IDB_MICBTN                      151
#define IDB_PPTOPEN                     152
#define IDB_RECORDSTOPBTN               153
#define IDB_RECORDBTN                   154
#define IDB_SHOWHIDETOOLBTN             156
#define IDB_MOVETOPBOTTOMBTN            157
#define IDB_HIGHLIGHTPEN                158
#define IDB_SHOWHIDEBG                  159
#define IDB_CONTROLBG                   160
#define IDB_SNAPSHOT                    161
#define IDB_EXIT                        162
#define IDB_PRINT                       163
#define IDB_SLIDEMENUBTN                164
#define IDB_LINEWEIGHTSELBG             165
#define IDB_BOARDSELBG                  166
#define IDB_COLORSELBG                  167
#define IDB_DIAGRAMSELBG                168
#define IDB_ERASERSELBG                 169
#define IDB_PENSELBG                    170
#define IDB_BRUSH                       171
#define IDB_UNDO                        172
#define IDB_ERASERALL                   173
#define IDB_ERASERRECT                  174
#define IDB_WRITEBOARD                  175
#define IDB_MUSICBOARD                  176
#define IDB_WHITEBOARD                  177
#define IDB_SNAPSHOTACTION              178
#define IDB_WMVBTN                      179
#define IDB_RECT                        180
#define IDB_ELLIPSE                     181
#define IDB_LINE                        182
#define IDB_RECORDPAUSEBTN              183
#define IDB_SLIDEMENUBG                 184
#define IDB_MOVEBOTTOMBTN               185
#define IDB_MOVETOPBTN                  186
#define IDB_HELPBTN                     187
#define IDB_SLIDEMENU_BOTTOMBG          188
#define IDB_SLIDEMENU_TOPBG             189
#define IDB_SLIDEMENUCAPBG              190
#define IDB_RECORDPROGRESS              191
#define IDD_WMVCONVERTDLG               192
#define IDB_WMVCONVBG                   193
#define IDB_WMVBROWSERBTN               194
#define IDB_WMVCANCELBTN                195
#define IDB_WMVNEXTBTN                  196
#define IDB_WMVPREVIEWBTN               197
#define IDB_WMVFINISHBTN                198
#define IDD_SAVEPROGRESSDLG             199
#define IDB_WMVCLOSEBTN                 200
#define IDD_REGISTRATIONDLG             201
#define IDB_LOGO                        202
#define IDD_OPTIONDLG                   203
#define IDB_OPTIONBG                    204
#define IDB_BGIMAGE1                    205
#define IDB_OPTIONBTN                   206
#define IDC_PENCURSOR                   207
#define IDC_BRUSHCURSOR                 208
#define IDC_HGPENCURSOR                 209
#define IDC_ERASERCURSOR                210
#define IDC_ERASER_RECTCURSOR           211
#define IDC_LINECURSOR                  212
#define IDC_RECTCURSOR                  213
#define IDC_ELLIPSECURSOR               214
#define IDB_OPTIONOKBTN                 215
#define IDC_TEXTCURSOR                  215
#define IDB_OPTIONCANCELBTN             216
#define IDB_OPTION_TOOLBARBTN           217
#define IDB_OPTION_ABOUTBTN             218
#define IDB_OPTION_HOTKEYBTN            219
#define IDB_OPTION_RECBTN               221
#define IDB_BGIMAGE2                    222
#define IDB_COMPANY                     223
#define IDB_SLIDEOPENBTN                224
#define IDD_RECORD_SELECTRANGE          225
#define IDB_CAMERA                      225
#define IDD_MAGNIFIERDLG                226
#define IDD_MAGNIFIERPREVIEWDLG         227
#define IDD_RECSIZEDLG                  229
#define IDD_OPT_LOGODLG                 231
#define IDB_OPTION_VIDEO                231
#define IDD_OPT_FOLDERDLG               232
#define IDB_OPTION_FOLDER               232
#define IDD_OPT_TEXTDLG                 233
#define IDB_OPTION_LOGO                 233
#define IDD_OPT_SOUNDDLG                234
#define IDB_OPTION_SNAPSHOT             234
#define IDD_OPT_SNAPSHOTDLG             235
#define IDB_OPTION_SOUND                235
#define IDD_OPT_CAMERADLG               236
#define IDB_OPTION_TEXT                 236
#define IDB_OPTION_CAMERA               238
#define IDB_TEXT                        239
#define IDD_TEXTDLG                     240
#define IDB_OPTION_PENBTN               240
#define IDD_OPT_CODECDLG                241
#define IDB_CLOSE                       242
#define IDB_RECORDRANGE                 243
#define IDB_OPTION_UPBTN                245
#define IDB_OPTION_DOWNBTN              246
#define IDB_SELBTN                      248
#define IDB_CANCELBTN                   250
#define IDB_BROSERBTN                   251
#define IDB_OKBTN                       252
#define IDC_SHOWHIDETOOLBTN             1000
#define IDC_MOVETOPBTN                  1001
#define IDC_MOVEBOTTOMBTN               1002
#define IDC_MODEBTN                     1003
#define IDC_PENBTN                      1004
#define IDC_HIGHLIGHTPEN                1005
#define IDC_TEXT                        1005
#define IDC_ERASERBTN                   1006
#define IDC_COLORCHANGEBTN              1007
#define IDC_LINEWEIGHTCHANGEBTN         1008
#define IDC_DIAGRAMBTN                  1009
#define IDC_RECORDBTN                   1010
#define IDC_RECORDSTOPBTN               1011
#define IDC_MICBTN                      1012
#define IDC_WMVBTN                      1013
#define IDC_PPTPREVBTN                  1014
#define IDC_PPTNEXTBTN                  1015
#define IDC_BOARDOPENBTN                1016
#define IDC_ZOOMBTN                     1017
#define IDC_SNAPSHOTBTN                 1018
#define IDC_PRINTBTN                    1019
#define IDC_SLIDEMENUBTN                1020
#define IDC_RECORDPAUSEBTN              1021
#define IDC_HELPBTN                     1022
#define IDC_AVIPATH_EDIT                1023
#define IDC_SLIDEOPENBTN                1023
#define IDC_WMVPATH_EDIT                1024
#define IDC_CAMERABTN                   1024
#define IDC_WMVPATHBROWSER              1025
#define IDC_WMVCOVPROGRESSBAR           1026
#define IDC_PREVIEWWMVBTN               1027
#define IDC_WMVCONV_NEXTBTN             1028
#define IDC_SAVEPROGRESSBAR             1029
#define IDC_AVIPATHBROWSER              1029
#define IDC_WMVCLOSEBTN                 1030
#define IDC_REGDLG_USERNAMEEDITOR       1033
#define IDC_REGDLG_PRODUCTCODEEDITOR    1034
#define IDC_OPTIONBTN                   1034
#define IDC_REGDLG_REGCODEEDITOR        1035
#define IDC_OPT_LOGOCHECKBTN            1036
#define IDC_OPT_PENCHECKBTN             1037
#define IDC_OPT_HLPENCHECKBTN           1038
#define IDC_OPT_ERASERCHECKBTN          1039
#define IDC_OPT_COLORCHECKBTN           1040
#define IDC_OPT_WIDTHCHECKBTN           1041
#define IDC_OPT_DIAGRAMCHECKBTN         1042
#define IDC_OPT_CONTROLCHECKBTN         1043
#define IDC_OPT_PPTCHECKBTN             1044
#define IDC_OPT_BOARDCHECKBTN           1045
#define IDC_OPT_SNAPSHOTCHECKBTN        1046
#define IDC_OPT_PRINTCHECKBTN           1047
#define IDC_OPT_CURSORCOMBO             1048
#define IDC_OPT_FPSCOMBO                1049
#define IDC_OPT_QUALITYCOMBO            1050
#define IDC_OPT_LOGOEDITOR              1051
#define IDC_OPT_CONTENTSEDITOR          1052
#define IDC_OPT_WARNINGEDITOR           1053
#define IDC_OPT_LOGOBROWBTN             1054
#define IDC_OPT_CONTENTSBROWBTN         1055
#define IDC_OPT_PATTERN1BTN             1056
#define IDC_OPT_PATTERN2BTN             1057
#define IDC_OPT_PATTERN3BTN             1058
#define IDC_OPT_PATTERN4BTN             1059
#define IDC_OPT_SLIDEEDITOR             1060
#define IDC_OPT_SLIDEBROWBTN            1061
#define IDC_OPTION_TOOLBARBTN           1062
#define IDC_OPTION_RECORDBTN            1063
#define IDC_OPTION_PENFOLDERBTN         1064
#define IDC_OPTION_PENBTN               1064
#define IDC_OPTION_HOTKEYBTN            1065
#define IDC_OPTION_ABOUTBTN             1066
#define IDC_OPTIONCLOSEBTN              1067
#define IDC_OPT_MODECHECKBTN            1068
#define IDC_OPTION_LOGOBTN              1068
#define IDC_OPTION_REGISTRATION         1069
#define IDC_OPTION_FOLDERBTN            1069
#define IDC_OPT_ZOOMCHECKBTN            1070
#define IDC_OPTION_TEXTBTN              1070
#define IDC_OPT_SNAPSHOTFULL            1071
#define IDC_OPTION_SOUNDBTN             1071
#define IDC_OPT_SNAPSHOTRANGE           1072
#define IDC_OPTION_SNAPSHOTBTN          1072
#define IDC_EXCLUSIVE_RECMODE           1073
#define IDC_OPTION_CAMERA               1073
#define IDC_NORMAL_RECMODE              1074
#define IDC_OPT_TOOLRECCHECKBTN         1074
#define IDC_RECORD_RANGE_FULL           1075
#define IDC_RECORD_RANGE_WINDOW         1076
#define IDC_RECORD_RANGE_AREA           1077
#define IDC_NORMAL_RECMODE2             1078
#define IDC_OPT_MIKEREC                 1080
#define IDC_OPT_MIXREC                  1081
#define IDC_OPT_CAMERA_SIZE0            1084
#define IDC_OPT_CAMERA_SIZE1            1085
#define IDC_OPT_CAMERA_SIZE2            1086
#define IDC_OPT_CAMERA_SIZE3            1087
#define IDC_SLIDE_SELECTBTN             1090
#define IDC_SLIDE_CANCELBTN             1091
#define IDC_OPTION_CODEC                1092
#define IDC_SLIDE_OPENBTN               1092
#define IDC_OPTION_DOWNBTN              1093
#define IDC_OPTION_UPBTN                1094
#define IDC_OPT_VIDEOCODEC_CHECK        1095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
